version: "3.9"  # optional since v1.27.0
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  arango:
    image: arangodb:3.9.0
    ports:
      - "8529:8529"
    # TODO: volumes:
    environment:
      - ARANGO_ROOT_USER=ml2wf_user
      - ARANGO_ROOT_PASSWORD=ml2wf_password

