version: "3.9"  # optional since v1.27.0
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  arango:
    image: arangodb:3.9.0
    ports:
      - "8529:8529"
    # TODO: volumes:
    environment:
      - ARANGO_ROOT_USER=ml2wf_user
      - ARANGO_ROOT_PASSWORD=ml2wf_password
  neo4j:
    image: neo4j:4.4.8
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/ml2wf_password

