true
compute descriptors over 5 min time windows=Light_Green
detect with OC_SVM Model=Light_Green
testCriteriaFeature=Orange
TimeSeriesReSampling=Light_Green
testTrainingStepFeature=Orange
preprocess data_Step=Light_Gray
ML_ALGO_TODEFINE=Cyan
train OC_SVM=Light_Green
criteria4OC_SVM=Light_Green
select training period=Light_Green
compute descriptors_Step=Light_Gray
NumberOfOutliers=NO_COLOR
